### ISSUE TITLE
Failed to load and run mob_miner/init.lua

### ISSUE THREAD

**Issue by nicsle** [sapier/animals_modpack#130]
Hi I got the following error when running minetest with animal modpack:

2016-05-31 23:24:40: ERROR[Main]: ModError: Failed to load and run script from /home/minetest/minetest/bin/../games/minetest/mods/animals_modpack/mob_miner/init.lua:
2016-05-31 23:24:40: ERROR[Main]: ...es/minetest/mods/mobf_core/mobf/utils/error_handling.lua:27: assertion failed!
2016-05-31 23:24:40: ERROR[Main]: stack traceback:
2016-05-31 23:24:40: ERROR[Main]:       [C]: in function 'assert'
2016-05-31 23:24:40: ERROR[Main]:       ...es/minetest/mods/mobf_core/mobf/utils/error_handling.lua:27: in function 'mobf_assert_backtrace'
2016-05-31 23:24:40: ERROR[Main]:       .../games/minetest/mods/animals_modpack/mob_miner/utils.lua:17: in main chunk
2016-05-31 23:24:40: ERROR[Main]:       [C]: in function 'dofile'
2016-05-31 23:24:40: ERROR[Main]:       ..../games/minetest/mods/animals_modpack/mob_miner/init.lua:27: in main chunk

I'm using minetest 0.4.14

**Comment by numberZero** [comment]
That’s because someone pushed broken commit. Try previous commit (`git checkout master^` IIRC) of `mobf_core` (not `animals_modpack`) or my fixed version (https://github.com/numberZero/mobf_core)

**Comment by Ginger88895** [comment]
Please fix this sapier?

**Comment by KabbAmine** [comment]
Is there any news here? I have the same error even with @numberZero fork, so the mod does not work.

**Comment by numberZero** [comment]
@KabbAmine make sure you use the proper branch (`patch-1`) of my fork. If so, please post the error message here, it may only look similar. Also tell the MT version you use.
@sapier please, please, pay attention to that old problem; that’s just a little mistake, but it can break things seriously (not only in the `animals_modpack` mod)

**Comment by KabbAmine** [comment]
Thanks for your interest @numberZero

```
minetest --version

Minetest 0.4.14 (Linux)
Using Irrlicht 1.8.3
Build info: VER=0.4.14 BUILD_TYPE=None RUN_IN_PLACE=0 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 STATIC_SHAREDIR="/usr/share/minetest"
```

I've managed to make it work using the `patch-1` branch but I still have some issues:

## Issue 1

Sometimes, I have the following errors:

```
2016-08-14 17:03:25: WARNING[Emerge-0]: Undeclared global variable "playerspawned" accessed at ...k-bag/.minetest/mods/animals_modpack/animal_dm/vault.lua:241
2016-08-14 17:03:26: ERROR[Server]: Map::setNode(): Not allowing to place CONTENT_IGNORE while trying to replace "default:tree" at (108,24,25) (block (6,1,1))
2016-08-14 17:03:26: ERROR[Server]: Map::setNode(): Not allowing to place CONTENT_IGNORE while trying to replace "default:tree" at (108,24,25) (block (6,1,1))
2016-08-14 17:03:26: ERROR[Server]: Map::setNode(): Not allowing to place CONTENT_IGNORE while trying to replace "default:tree" at (108,24,25) (block (6,1,1))
```

And they disappear after restarting the game.

## Issue 2

I have some mobs that are badly(?) spawned (I presume that they are mobs):

![sp](https://cloud.githubusercontent.com/assets/5658084/17649604/99269778-624a-11e6-8c78-aac05448769f.png)

Sometimes when I punch them, it gives me those errors:

```
2016-08-14 17:19:59: ERROR[Server]: ServerEnvironment::deactivateFarObjects(): id=1359 m_static_exists=true but static data doesn't actually exist in (16,1,17)
2016-08-14 17:19:59: WARNING[Server]: StaticObjectList::remove(): id=1359 not found
2016-08-14 17:19:59: ERROR[Server]: ServerEnvironment::deactivateFarObjects(): id=1360 m_static_exists=true but static data doesn't actually exist in (16,1,17)
2016-08-14 17:19:59: WARNING[Server]: StaticObjectList::remove(): id=1360 not found
```

## Issue 3

The door in the stores are considered as unknown

![store](https://cloud.githubusercontent.com/assets/5658084/17649630/ee519298-624a-11e6-80a1-9188b58d9ff6.png)

I have the `doors` mod (Present by default)

-------------------------------------

My son is playing with the `mobs_redo` mod + a lot of mobs (animals, monsters....) and it works really great, but we want to play `animals_modpack` because of the breeding system and the store so it will be great to make it work.

If needed, we can separate the issues in separate ones, even if the repository is rarely updated.

**Comment by numberZero** [comment]
1. Looks like mapgen-time errors. Should be harmless.
2. I think that is SPawner.
  - About static data: developers say that’s due to MT core bug. Know little about that.
3. Because these are old-style (before 2016) doors. There is an automatic conversion code, but it didn’t worked here. @sofar any ideas why it doesn’t work in this case?

**Comment by sofar** [comment]
Likely the code doesn't use the old door API, but created a duplicate registration call manually, thus bypassing the conversion code.

**Comment by numberZero** [comment]
it doesn’t register the doors, it only places them. Places `doors:door_wood_t_1` and `doors:door_wood_b_1` blocks.
I think I will write a patch to fix that soon

**Comment by KabbAmine** [comment]
> it doesn’t register the doors, it only places them. Places doors:door_wood_t_1 and doors:door_wood_b_1 blocks.
> I think I will write a patch to fix that soon

Great, we'll wait for a fix then

**Comment by numberZero** [comment]
Fixed. See https://github.com/numberZero/animals_modpack/tree/fix-doors (and #136)

**Comment by KabbAmine** [comment]
@numberZero Better but still not working :smile: 

The door appears correctly but the game exits when I try to open it.

```
2016-08-21 17:16:20: ERROR[Main]: ServerError: Lua: Runtime error from mod '' in callback item_OnPlace(): /usr/share/minetest/games/minetest_game/mods/doors/init.lua:159: attempt to perform arithmetic on local 'state' (a string value)
2016-08-21 17:16:20: ERROR[Main]: stack traceback:
2016-08-21 17:16:20: ERROR[Main]: 	/usr/share/minetest/games/minetest_game/mods/doors/init.lua:159: in function 'door_toggle'
2016-08-21 17:16:20: ERROR[Main]: 	/usr/share/minetest/games/minetest_game/mods/doors/init.lua:359: in function 'on_rightclick'
2016-08-21 17:16:20: ERROR[Main]: 	/usr/share/minetest/builtin/game/item.lua:333: in function </usr/share/minetest/builtin/game/item.lua:326>
```

**Comment by numberZero** [comment]
Works for me. Make sure you have the latest version of `minetest_game` (at least this commit: https://github.com/minetest/minetest_game/commit/7681682d28e87c23f7e986ac25cb21f8d51b883c)

**Comment by sofar** [comment]
@KabbAmine that was an issue in older `minetest_game` code for doors.

**Comment by sapier** [comment]
I merged the suggested fixes in current master it's gonna be included in 2.5.2 release
